services:
  shadcn-mono-1-app:
    build:
      context: ./shadcn-mono-1
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    working_dir: /app/shadcn-mono-1/
    volumes:
      - .:/app
      # - /app/shadcn-mono-1/node_modules
    command: sh -c "pnpm install && pnpm dev"

  shadcn-mono-1-storybook:
    build:
      context: ./shadcn-mono-1
      dockerfile: docker/Dockerfile.dev
    ports:
      - "6006:6006"
    working_dir: /app/shadcn-mono-1/
    volumes:
      - .:/app
      # - /app/shadcn-mono-1/node_modules
    command: sh -c "pnpm install && pnpm storybook --ci"
