FROM node:22-alpine

WORKDIR /app

# Copy only package manager files first to leverage Docker caching
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Copy the entire project
COPY . .

RUN pnpm install --force
