services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm install && pnpm dev"

  storybook:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm install && pnpm storybook --ci"
